name: Compare Folder Contents

on:
  workflow_dispatch:
    inputs:
      trigger: # You can customize the trigger name if needed
        description: 'Run manually'
        required: true

jobs:
  compare-folder-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # You can specify the Python version you need

    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install -r requirements.txt  # If you have any dependencies, add them to requirements.txt

    - name: Compare Folder Contents
      run: |
        python -c "import glob; folder = 'results/*.csv'; result1 = glob.glob(folder); result2 = sorted(glob.glob(folder)); print(result1); print(result2); print(result1 == result2)"

